export const CORE_AUTH_SIGN_IN = "CORE_AUTH_SIGN_IN";
export const CORE_AUTH_OK = "CORE_AUTH_OK";
export const CORE_AUTH_ERROR = "CORE_AUTH_ERROR";
export const CORE_AUTH_SIGN_OUT = "CORE_AUTH_SIGN_OUT";

export const CORE_APP_INITIALISED = "CORE_APP_INITIALISED";
export const CORE_APP_INITIALISE_PROGRESS = "CORE_APP_INITIALISE_PROGRESS";
export const CORE_APP_TOGGLE_THEME = "CORE_APP_TOGGLE_THEME";

export const CORE_SERVER_PENDING = "CORE_SERVER_PENDING";
export const CORE_SERVER_ERROR = "CORE_SERVER_ERROR";
export const CORE_SERVER_IDLE = "CORE_SERVER_IDLE";
