export const CORE_AUTH_AUTHENTICATING = "CORE_AUTH_AUTHENTICATING";
export const CORE_AUTH_AUTHENTICATED = "CORE_AUTH_AUTHENTICATED";
export const CORE_AUTH_ERROR = "CORE_AUTH_ERROR";
export const CORE_AUTH_SIGN_OUT = "CORE_AUTH_SIGN_OUT";

export const CORE_APP_RESET = "CORE_APP_RESET";
export const CORE_APP_INITIALISED = "CORE_APP_INITIALISED";
export const CORE_APP_USER_INITIALISED = "CORE_APP_USER_INITIALISED";
export const CORE_APP_INITIALISE_PROGRESS = "CORE_APP_INITIALISE_PROGRESS";
export const CORE_APP_TOGGLE_THEME = "CORE_APP_TOGGLE_THEME";
export const CORE_APP_SET_FEEDBACK = "CORE_APP_SET_FEEDBACK";
export const CORE_APP_HIDE_FEEDBACK = "CORE_APP_HIDE_FEEDBACK";
export const CORE_APP_SET_PERMISSIONS = "CORE_APP_SET_PERMISSIONS";
